version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/build-ci-image"
      - "/.github/actions/merge-ci-images"
    schedule:
      interval: "weekly"
