coverage:
  range: "90..98"
  precision: 1
  round: nearest
  status:
    project:
      default:
        target: 99%
        threshold: 1%

    patch:
      default:
        target: auto
        threshold: 1%

parsers:
  cobertura:
    partials_as_hits: false
    handle_missing_conditions: false

ignore:
  - "external/"
  - "tests/"
