version: 3

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    only:
      - "**/*.hpp"
      - "**/*.cpp"
      - "**/*.cmake"
      - "**/LICENSE*"
    exclude:
      - ".git/**"
