# Based on https://docs.docker.com/build/ci/github-actions/multi-platform/

name: merge-ci-images
description: Merge CI images built for different platforms into a single multi-arch image.

inputs:
  image:
    required: true
    description: The name of the image to build, e.g. "libfn.azurecr.io/ci-build-gcc".
  tags:
    required: true
    description: The tags to apply to the image, e.g. "16".
  registry:
    required: true
    description: The registry to push the image to, e.g. "docker.io" or "libfn.azurecr.io".
  username:
    required: true
    description: The username for the registry.
  password:
    required: true
    description: The password or token for the registry.
  title:
    required: true
    description: A title to include in the image metadata, e.g. "build-gcc-16".

runs:
  using: composite
  steps:
    - name: Download digests
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        path: /tmp/digests
        pattern: digests-${{ inputs.title }}-*
        merge-multiple: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
      with:
        images: ${{ inputs.image }}
        tags: ${{ inputs.tags }}

    - name: Login to Docker Hub
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password  }}

    - name: Create manifest list and push
      working-directory: /tmp/digests
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
      run: |
        docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf "${IMAGE}@sha256:%s " *)

    - name: Inspect image
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
      run: |
        docker buildx imagetools inspect ${IMAGE}:${{ steps.meta.outputs.version }}
