# Based on https://docs.docker.com/build/ci/github-actions/multi-platform/

name: merge-ci-images

inputs:
  image:
    default: null
    required: true
    type: string
  tags:
    default: null
    required: true
  username:
    default: null
    required: true
    type: string
  password:
    default: null
    required: true
    type: string
  title:
    default: null
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Download digests
      uses: actions/download-artifact@v4
      with:
        path: /tmp/digests
        pattern: digests-${{ inputs.title }}-*
        merge-multiple: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image }}
        tags: ${{ inputs.tags }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password  }}

    - name: Create manifest list and push
      working-directory: /tmp/digests
      shell: bash
      run: |
        docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf '${{ inputs.image }}@sha256:%s ' *)

    - name: Inspect image
      shell: bash
      run: |
        docker buildx imagetools inspect ${{ inputs.image }}:${{ steps.meta.outputs.version }}
