name: build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'include/**'
      - 'tests/**'
      - 'examples/**'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'nix/**'
      - 'flake.nix'
      - 'flake.lock'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'include/**'
      - 'tests/**'
      - 'examples/**'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'nix/**'
      - 'flake.nix'
      - 'flake.lock'

jobs:
  linux:
    runs-on:
      group: runners-arm64
    strategy:
      fail-fast: false
      matrix:
        mode:
          - cxx20
          - cxx23
        configuration:
          - Debug
          - Release
        compiler:
          - "gcc:12"
          - "clang:16"
          - "clang:17"
          - "gcc:13"
          - "gcc:14"
          - "gcc:15"
          - "gcc:16"
          - "clang:18"
          - "clang:19"
          - "clang:20"
          - "clang:21"
          - "clang:22"
          - "clang-libstdcxx:21"
          - "clang-libstdcxx:22"
        exclude:
          - mode: cxx23
            compiler: "gcc:12"
          - mode: cxx23
            compiler: "clang:16"
          - mode: cxx23
            compiler: "clang:17"
        include:
          - mode: all
            configuration: Debug
            compiler: "gcc:14"
          - mode: all
            configuration: Release
            compiler: "gcc:14"
    container: libfn.azurecr.io/ci-build-${{ matrix.compiler }}
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Prepare build
      run: |
        mkdir .build
        cd .build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} ${{ matrix.mode == 'cxx20' && '-DDISABLE_CXX23=ON' || '' }} ..
        COMPILER=$( grep -iE "^CMAKE_CXX_COMPILER:FILEPATH=" CMakeCache.txt | sed -n 's/^[^=]*=//p' )
        FLAGS=$( grep -iE "^CMAKE_CXX_FLAGS(_${{ matrix.configuration }})?:STRING" CMakeCache.txt | sed -n 's/^[^=]*=//p' | tr '\n' ' ' )
        printf "C++ compiler path: %s\n" "$COMPILER"
        "$COMPILER" --version
        printf "C++ compilation options: %s\n" "$FLAGS"

    - name: Build and test ${{ matrix.mode }}
      if: matrix.mode != 'all'
      run: |
        cd .build
        cmake --build . --target ${{ matrix.mode }}
        ctest -L ${{ matrix.mode }} --output-on-failure

    # Build and test all for one arbitrary configuration
    - name: Build and test all
      if: matrix.mode == 'all'
      run: |
        cd .build
        cmake --build .
        ctest --output-on-failure

  macos:
    runs-on: macos-${{ matrix.compiler.osver }}
    strategy:
      fail-fast: false
      matrix:
        mode:
          - cxx20
          - cxx23
        configuration:
          - Debug
          - Release
        compiler:
          - name: appleclang
            osver: 14
          - name: appleclang
            osver: 15
          - name: appleclang
            osver: 26
          - name: clang
            osver: 15
            release: 18
          - name: clang
            osver: 26
            release: 20
        exclude:
          - mode: cxx23
            compiler:
              name: appleclang
              osver: 14
        include:
          - mode: all
            configuration: Debug
            compiler:
              name: appleclang
              osver: 15
          - mode: all
            configuration: Release
            compiler:
              name: appleclang
              osver: 15
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Prepare build
      run: |
        mkdir .build
        cd .build
        if [[ "${{ matrix.compiler.name }}" == "appleclang" ]]; then
          CXX="$(which clang++)"
          CC="$(which clang)"
          export CXX CC
        fi
        if [[ "${{ matrix.compiler.name }}" == "clang" ]]; then
          CXX="$(brew --prefix llvm@${{ matrix.compiler.release }})/bin/clang++"
          CC="$(brew --prefix llvm@${{ matrix.compiler.release }})/bin/clang"
          export CXX CC
        fi
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} ${{ matrix.mode == 'cxx20' && '-DDISABLE_CXX23=ON' || '' }} ..
        COMPILER=$( grep -iE "^CMAKE_CXX_COMPILER:FILEPATH=" CMakeCache.txt | sed -n 's/^[^=]*=//p' )
        FLAGS=$( grep -iE "^CMAKE_CXX_FLAGS(_${{ matrix.configuration }})?:STRING" CMakeCache.txt | sed -n 's/^[^=]*=//p' | tr '\n' ' ' )
        printf "C++ compiler path: %s\n" "$COMPILER"
        "$COMPILER" --version
        printf "C++ compilation options: %s\n" "$FLAGS"

    - name: Build and test ${{ matrix.mode }}
      if: matrix.mode != 'all'
      run: |
        cd .build
        cmake --build . --target ${{ matrix.mode }}
        ctest -L ${{ matrix.mode }} --output-on-failure

    # Build and test all for one arbitrary configuration
    - name: Build and test all
      if: matrix.mode == 'all'
      run: |
        cd .build
        cmake --build .
        ctest --output-on-failure

  windows:
      runs-on: ${{ matrix.vs.runner }}
      strategy:
        fail-fast: false
        matrix:
          mode:
            - cxx20
          configuration:
            - Debug
            - Release
          vs:
            - generator: "Visual Studio 17 2022"
              runner: "windows-2022"
            - generator: "Visual Studio 18 2026"
              runner: "windows-2025-vs2026"

      steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Prepare build
        shell: bash
        run: |
          mkdir .build
          cd .build
          cmake -G "${{ matrix.vs.generator }}" -A x64 -DDISABLE_CXX23=ON ..
          LINKER=$( grep -iE "^CMAKE_LINKER:FILEPATH=" CMakeCache.txt | sed -n 's/^[^=]*=//p' )
          FLAGS=$( grep -iE "^CMAKE_CXX_FLAGS(_${{ matrix.configuration }})?:STRING" CMakeCache.txt | sed -n 's/^[^=]*=//p' | tr '\n' ' ' )
          printf "C++ linker path: %s\n" "$LINKER"
          "$LINKER" . || true
          printf "C++ compilation options: %s\n" "$FLAGS"

      - name: Build and test ${{ matrix.mode }}
        shell: bash
        run: |
          cd .build
          cmake --build . --target ${{ matrix.mode }} --config ${{ matrix.configuration }}
          ctest -L ${{ matrix.mode }} -C ${{ matrix.configuration }} --output-on-failure

  nixos:
    runs-on:
      group: runners-intel
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc
          - clang
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Install Nix
      uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Build and test
      run: nix -L build '.#${{matrix.compiler}}'
