name: ci-docs

on:
  schedule:
  # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
  # This is meant to run at 14:17 UTC on 11th and 26th of every month
    - cron: '17 14 11 * *'
    - cron: '17 14 26 * *'
  push:
    branches:
      - main
    paths:
      - '.github/actions/build-ci-image/**'
      - '.github/actions/merge-ci-images/**'
      - '.github/workflows/ci-docs.yml'
      - 'ci/docs/**'
      - 'ci/build-catch.sh'
      - 'ci/fetch-node.sh'
  workflow_dispatch:

env:
  REGISTRY_IMAGE: libfn.azurecr.io/ci-docs
  DEBIAN_VERSION: trixie
  JAVA_VERSION: openjdk-21-jdk
  DOXYGEN_RELEASE: 1.12.0
  ZNAI_RELEASE: 1.73
  CATCH_RELEASE: 3.14.0
  NODE_RELEASE: 24

jobs:
  build:
    if: ${{ github.repository == 'libfn/functional' }}
    runs-on:
      group: ${{ matrix.platform == 'linux/arm64' && 'runners-arm64' || 'runners-intel' }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          sparse-checkout: .github

      - uses: ./.github/actions/build-ci-image
        with:
          platform: ${{ matrix.platform }}
          image: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
          registry: libfn.azurecr.io
          username: ${{ secrets.AZURECR_NAME }}
          password: ${{ secrets.AZURECR_PASS }}
          build_args: |
            DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}
            JAVA_VERSION=${{ env.JAVA_VERSION }}
            DOXYGEN_RELEASE=${{ env.DOXYGEN_RELEASE }}
            ZNAI_RELEASE=${{ env.ZNAI_RELEASE }}
            CATCH_RELEASE=${{ env.CATCH_RELEASE }}
            NODE_RELEASE=${{ env.NODE_RELEASE }}
          context: "ci"
          file: "docs/Dockerfile"
          title: "docs"
          push: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}

  merge:
    if: ${{ github.repository == 'libfn/functional' && github.ref_type == 'branch' && github.ref_name == 'main' }}
    runs-on:
      group: runners-intel
    needs:
      - build

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          sparse-checkout: .github

      - uses: ./.github/actions/merge-ci-images
        with:
          image: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
          registry: libfn.azurecr.io
          username: ${{ secrets.AZURECR_NAME }}
          password: ${{ secrets.AZURECR_PASS }}
          title: "docs"
