name: license

on:
  push:
    paths:
      - '.fossa.yml'
      - 'LICENSE*'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - '*.cpp'
      - '*.hpp'
      - '*.ipp'

jobs:
  license-check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - uses: fossas/fossa-action@v1
      with:
        api-key: ${{ secrets.FOSSA_API_KEY }}
