name: license

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-license-compliance:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - uses: fossas/fossa-action@main
      with:
        api-key: ${{ secrets.FOSSA_API_KEY }}
