name: nix

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/nix.yml'
      - 'nix/**'
      - 'include/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'README.md'
      - 'LICENSE.md'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/nix.yml'
      - 'nix/**'
      - 'include/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'README.md'
      - 'LICENSE.md'

jobs:
  build:
    runs-on:
      group: runners-intel
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - gcc
        - clang
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Build and test
      run: nix -L build '.#${{matrix.compiler}}'
