name: package-test-nix

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/package-test-nix.yml'
      - 'test_package/**'
      - 'include/**'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'nix/**'
      - 'flake.nix'
      - 'flake.lock'
      - 'VERSION'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/package-test-nix.yml'
      - 'test_package/**'
      - 'include/**'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'nix/**'
      - 'flake.nix'
      - 'flake.lock'
      - 'VERSION'
  workflow_dispatch:

jobs:
  test_nix:
    runs-on:
      group: runners-intel

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v4

    - name: nix package test (disable_cxx23=False)
      run: nix -L build './test_package#consumer'
        --override-input libfn "git+file://$(pwd)?rev=${{ github.sha }}"

    - name: nix package test (disable_cxx23=True)
      run: nix -L build './test_package#consumer-no-cxx23'
        --override-input libfn "git+file://$(pwd)?rev=${{ github.sha }}"
