name: package-test-nix

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/package-test-nix.yml'
      - 'test_package/**'
      - 'include/**'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'nix/**'
      - 'flake.nix'
      - 'flake.lock'
      - 'VERSION'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/package-test-nix.yml'
      - 'test_package/**'
      - 'include/**'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'nix/**'
      - 'flake.nix'
      - 'flake.lock'
      - 'VERSION'
  workflow_dispatch:

jobs:
  test_nix:
    runs-on:
      group: runners-intel
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: cxx23
            target: consumer
          - name: cxx20
            target: consumer-no-cxx23
          - name: cxx20-std23
            target: consumer-no-cxx23-std23

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Test ${{ matrix.name }} packaging
      run: |
        nix -L build './test_package#${{ matrix.target }}' \
          --override-input libfn "git+file://$(pwd)?rev=${{ github.sha }}&shallow=1"
