name: package-test-bazel

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/package-test-bazel.yml'
      - 'MODULE.bazel'
      - 'BUILD.bazel'
      - 'test_package/**'
      - 'include/**'
      - 'VERSION'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/package-test-bazel.yml'
      - 'MODULE.bazel'
      - 'BUILD.bazel'
      - 'test_package/**'
      - 'include/**'
      - 'VERSION'
  workflow_dispatch:

env:
  BAZEL_RELEASE: 8.7.0

jobs:
  test_bazel:
    runs-on: ${{ github.repository == 'libfn/functional' && 'warp-ubuntu-latest-x64-4x' || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - ci-build-gcc-bazel:16
          - ci-build-clang-bazel:22
    container: libfn.azurecr.io/${{ matrix.image }}-sha-08b1133
    defaults:
      run:
        working-directory: test_package
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Set Bazel version
      run: |
        echo "USE_BAZEL_VERSION=${{ env.BAZEL_RELEASE }}" >> "${GITHUB_ENV}"

    - name: Test C++23 packaging
      run: |
        bazel run --cxxopt=-std=c++23 //:pfn_quine
        bazel run --cxxopt=-std=c++23 //:fn_quine

    - name: Test C++20 packaging
      run: |
        bazel run --cxxopt=-std=c++20 //:pfn_quine
