name: package-test-conan

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/package-test-conan.yml'
      - 'conanfile.py'
      - 'test_package/**'
      - 'include/**'
      - 'VERSION'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/package-test-conan.yml'
      - 'conanfile.py'
      - 'test_package/**'
      - 'include/**'
      - 'VERSION'
  workflow_dispatch:

jobs:
  test_conan:
    runs-on:
      group: runners-intel
    container: libfn.azurecr.io/ci-build-gcc:15
    steps:
    - uses: actions/checkout@v4

    - name: Detect Conan profile
      run: |
        conan profile detect
        echo "tools.cmake.cmaketoolchain:generator=Ninja" >> ~/.conan2/global.conf

    - name: Test C++23 packaging
      run: conan create . --build=missing -o "&:disable_cxx23=False" -s "compiler.cppstd=23"

    - name: Test C++20 packaging
      run: conan create . --build=missing -o "&:disable_cxx23=True" -s "compiler.cppstd=20"

    - name: Test C++20 packaging with C++23 compiler
      run: conan create . --build=missing -o "&:disable_cxx23=True" -s "compiler.cppstd=23"
