name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checks:
    runs-on: ${{ github.repository == 'libfn/functional' && 'warp-ubuntu-latest-arm64-2x' || 'ubuntu-latest' }}
    container: libfn.azurecr.io/ci-pre-commit:sha-08b1133

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Prepare
      run: |
        # Required because of https://github.com/actions/checkout/issues/766
        git config --global --add safe.directory "${GITHUB_WORKSPACE}"
        pip freeze --local

    - name: Apply pre-commit
      run: |
        pre-commit run --show-diff-on-failure --color=always --all-files
