name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checks:
    runs-on: ${{ github.repository == 'libfn/functional' && 'warp-ubuntu-latest-arm64-2x' || 'ubuntu-latest' }}
    container: libfn.azurecr.io/ci-pre-commit:sha-95f599d

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Prepare
      run: |
        # Required because of https://github.com/actions/checkout/issues/766
        git config --global --add safe.directory "${GITHUB_WORKSPACE}"
        pip freeze --local

    - name: Apply pre-commit
      run: |
        pre-commit run --show-diff-on-failure --color=always --all-files
